<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Event Calendar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">

    <link rel="stylesheet" href="../assets/css/normalize.css">
    <link rel="stylesheet" href="../assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="../assets/css/themify-icons.css">
    <link rel="stylesheet" href="../assets/css/flag-icon.min.css">
    <link rel="stylesheet" href="../assets/css/cs-skin-elastic.css">
    <!-- <link rel="stylesheet" href="assets/css/bootstrap-select.less"> -->
    <link href="../assets/css/lib/vector-map/jqvmap.min.css" rel="stylesheet">
    <!-- <link rel="stylesheet" href="main.css"> -->
    <link href="../assets/scss/style.css" rel="stylesheet">
    <link href='../assets/css/open-sans.css' rel='stylesheet' type='text/css'>

    <!-- <script type="text/javascript" src="https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js"></script> -->

    <!-- Start: Calendar related -->
    <link href="assets/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <link href='assets/fullcalendar/packages/core/main.css' rel='stylesheet' />
    <link href='assets/fullcalendar/packages/daygrid/main.css' rel='stylesheet' />
    <link href='assets/fullcalendar/packages/timegrid/main.css' rel='stylesheet' />
    <link href='assets/fullcalendar/packages/list/main.css' rel='stylesheet' />
    <link href='assets/css/calendar.css' rel='stylesheet' />
    <!-- End: Calendar related -->


</head>

<body>
    <!-- Left Panel -->
    <?php
    include dirname(__DIR__) . '\..\include\left_panel.php';
    ?>
    <div id="right-panel" class="right-panel">
        <!-- Header-->
        <header id="header" class="header">

            <div class="header-menu">

                <div class="col-sm-7">
                    <a id="menuToggle" class="menutoggle pull-left"><i class="fa fa fa-tasks"></i></a>
                    <div class="header-left">
                        <button class="search-trigger"><i class="fa fa-search"></i></button>
                        <div class="form-inline">
                            <form class="search-form">
                                <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                                <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                            </form>
                        </div>

                        <div class="dropdown for-notification">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-bell"></i>
                                <span class="count bg-danger">5</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="notification">
                                <p class="red">You have 3 Notification</p>
                                <a class="dropdown-item media bg-flat-color-1" href="#">
                                    <i class="fa fa-check"></i>
                                    <p>Server #1 overloaded.</p>
                                </a>
                                <a class="dropdown-item media bg-flat-color-4" href="#">
                                    <i class="fa fa-info"></i>
                                    <p>Server #2 overloaded.</p>
                                </a>
                                <a class="dropdown-item media bg-flat-color-5" href="#">
                                    <i class="fa fa-warning"></i>
                                    <p>Server #3 overloaded.</p>
                                </a>
                            </div>
                        </div>

                        <div class="dropdown for-message">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="ti-email"></i>
                                <span class="count bg-primary">9</span>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="message">
                                <p class="red">You have 4 Mails</p>
                                <a class="dropdown-item media bg-flat-color-1" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/1.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Jonathan Smith</span>
                                        <span class="time float-right">Just now</span>
                                        <p>Hello, this is an example msg</p>
                                    </span>
                                </a>
                                <a class="dropdown-item media bg-flat-color-4" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/2.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Jack Sanders</span>
                                        <span class="time float-right">5 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                    </span>
                                </a>
                                <a class="dropdown-item media bg-flat-color-5" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/3.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Cheryl Wheeler</span>
                                        <span class="time float-right">10 minutes ago</span>
                                        <p>Hello, this is an example msg</p>
                                    </span>
                                </a>
                                <a class="dropdown-item media bg-flat-color-3" href="#">
                                    <span class="photo media-left"><img alt="avatar" src="images/avatar/4.jpg"></span>
                                    <span class="message media-body">
                                        <span class="name float-left">Rachel Santos</span>
                                        <span class="time float-right">15 minutes ago</span>
                                        <p>Lorem ipsum dolor sit amet, consectetur</p>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-sm-5">
                    <div class="user-area dropdown float-right">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <img class="user-avatar rounded-circle" src="../images/admin.jpg" alt="User Avatar">
                        </a>

                        <div class="user-menu dropdown-menu">
                            <a class="nav-link" href="#"><i class="fa fa- user"></i>My Profile</a>
                            <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>
                            <a class="nav-link" href="#"><i class="fa fa-power -off"></i>Logout</a>
                        </div>
                    </div>

                    <div class="language-select dropdown" id="language-select">
                        <a class="dropdown-toggle" href="#" data-toggle="dropdown" id="language" aria-haspopup="true" aria-expanded="true">
                            <i class="flag-icon flag-icon-us"></i>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="language">
                            <div class="dropdown-item">
                                <span class="flag-icon flag-icon-fr"></span>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-es"></i>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-us"></i>
                            </div>
                            <div class="dropdown-item">
                                <i class="flag-icon flag-icon-it"></i>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </header><!-- /header -->
        <!-- Header-->

        <div class="breadcrumbs">
            <div class="col-sm-4">
                <div class="page-header float-left">
                    <div class="page-title">
                        <h1>Event Calendar</h1>
                    </div>
                </div>
            </div>
            <div class="col-sm-8">
                <div class="page-header float-right">
                    <div class="page-title">
                        <ol class="breadcrumb text-right">
                            <li class="active"></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            <div class="col-md-12 mt-4">
                <div id='loading'>loading...</div>
                <div id="calendar"></div>
            </div>

        </div>
    </div>
    <div id="addEventModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="..." aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Add Event</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="addEventForm">
                    <div class="modal-body">
                        <div class="col-md-12">
                            <div class="form-group row">
                                <label for="eventName" class="col-sm-4 col-form-label">Event name:* </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="eventName" name="eventName" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="allday" class="col-sm-4 col-form-label">All day event: </label>
                                <div class="col-sm-8">
                                    <label class="switch">
                                        <input type="checkbox" id="allday" name="allday" value="true">
                                        <span class="slider round"></span>
                                    </label>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="courseDesc" class="col-sm-4 col-form-label">Course Description: </label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" id="courseDesc" name="courseDesc"></textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="startTime" class="col-sm-4 col-form-label">Start date/time:* </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="startTime" name="startTime" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="endTime" class="col-sm-4 col-form-label">End date/time: </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="endTime" name="endTime">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="certifiedBy" class="col-sm-4 col-form-label">Certified by: </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="certifiedBy" name="certifiedBy">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="extUrl" class="col-sm-4 col-form-label">External URL: </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control" id="extUrl" name="extUrl">
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <input type="submit" class="btn btn-success" value="Save">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div id="eventDetailsModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="..." aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Event Details</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="eventDetailsForm">
                    <div class="modal-body">
                        <div class="col-md-12">
                            <div class="form-group row">
                                <label for="eventName2" class="col-sm-4 col-form-label">Event name:* </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control-plaintext" id="eventName2" name="eventName2" readonly>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="allday2" class="col-sm-4 col-form-label">All day event: </label>
                                <div class="col-sm-8">
                                    <i class="fa fa-check fa-2" aria-hidden="true" id="tick"></i>
                                    <i class="fa fa-times fa-2" aria-hidden="true" id="cross"></i>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="courseDesc2" class="col-sm-4 col-form-label">Course Description: </label>
                                <div class="col-sm-8">
                                    <textarea class="form-control-plaintext" id="courseDesc2" name="courseDesc2" readonly></textarea>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="startTime2" class="col-sm-4 col-form-label">Start date/time:* </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control-plaintext" id="startTime2" name="startTime2" readonly>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="endTime2" class="col-sm-4 col-form-label">End date/time: </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control-plaintext" id="endTime2" name="endTime2" readonly>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="certifiedBy2" class="col-sm-4 col-form-label">Certified by: </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control-plaintext" id="certifiedBy2" name="certifiedBy2" readonly>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="extUrl2" class="col-sm-4 col-form-label">External URL: </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control-plaintext" id="extUrl2" name="extUrl2" readonly>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button class="btn btn-primary" id="updateEventBtn">Update</button>
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="../assets/js/jquery.min.js"></script>
    <script src="../assets/js/popper.min.js"></script>

    <!-- Start: Calendar related -->
    <script src="assets/js/bootstrap.min.js"></script>
    <!-- End: Calendar related -->

    <script src="../assets/js/plugins.js"></script>
    <script src="../assets/js/main.js"></script>

    <!-- Start: Calendar related -->
    <script src="assets/js/superagent.js"></script>
    <script src="assets/js/moment.js"></script>
    <script src="assets/js/bootstrap-datetimepicker.min.js"></script>

    <script src='assets/fullcalendar/packages/core/main.js'></script>
    <script src='assets/fullcalendar/packages/interaction/main.js'></script>
    <script src='assets/fullcalendar/packages/daygrid/main.js'></script>
    <script src='assets/fullcalendar/packages/timegrid/main.js'></script>
    <script src='assets/fullcalendar/packages/list/main.js'></script>

    <script src="assets/js/calendar.js"></script>
    <!-- End: Calendar related -->
</body>

</html>